exclude: '.pixi/'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: local
  hooks:
  - id: ruff
    name: ruff-format
    stages: [pre-commit, pre-push]
    language: system
    entry: pixi run fmt
    types: [python]
    pass_filenames: false

  - id: ruff
    name: ruff-check
    stages: [pre-commit, pre-push]
    language: system
    entry: pixi run lint
    types: [python]
    pass_filenames: false

  - id: ty
    name: ty
    stages: [pre-commit, pre-push]
    language: system
    entry: pixi run types
    types: [python]
    pass_filenames: false

  - id: pytest
    name: pytest
    stages: [pre-commit, pre-push]
    language: system
    entry: pixi run test
    types: [python]
    pass_filenames: false
